### ISSUE TITLE
Manufacture the Paneling 

### ISSUE THREAD

**Issue by yomn61** [umigv/goat#224]
If needs to be laser cut, make sure Nick VanDyke or someone with access to a laser cutter knows about the plan finish the necessary things to make that happen.
If needs to be machined, make sure Madhav, Cameron, Daniel, etc knows about the part and make a part drawing for them to make.
The paneling material needs to be here by TBD and the paneling manufacturing procedures needs to be completed by TBD

**Comment by camkab** [comment]
Can be done in fabrication studio in the dude

**Comment by camkab** [comment]
Top plate and bottom plate will be laser cut out of HDPE on Saturday (HDPE picked up on Friday, ordered on 3/21) according to Cameron's coordination with the larger laser cutter.
Power shelf will be laser cut at the same time as the top and bottom plates.
The plates will be cut to shape, but not necessarily have holes for standoffs-those can be drilled by hand as needed.
The sides and front/back will be handled later (will not hold back teleop requirement by 3/28), likely in the Dude laser cutter.

**Comment by camkab** [comment]
Moved Milestone from Week 13 to Week 14 as these are not mission critical parts to have done, and am anticipating lead time on material.

**Comment by camkab** [comment]
Will Need to buy from home depot/other foam weather striping to weather proof frame

**Comment by camkab** [comment]
Thickness decided on: 1/8"
Material: Undecided, looking for update post leads meeting
Logos and Designs:Undecided, looking for update post leads meeting

**Comment by yomn61** [comment]
Mish will have bought it by this time

**Comment by camkab** [comment]
Mish ordered: 
one  24" x 48" x .125" Black HDPE Sheet
one  24" x 24" x .125" Black HDPE Sheet

Both from Grainger

**Comment by yomn61** [comment]
We wont be able to laser cut that in the Dude will we? That would have to be done on the huge laser cutter

**Comment by camkab** [comment]
It will be laser cut with the larger bed. I can get it cut Wednesday because I can't get access to it until Wednesday night.

**Comment by camkab** [comment]
Planning to get laser cut Tuesday (4/10) or Wednesday(4/11) night as per laser cutter availability.
Working on positioning the vents so that there is proper clearance from bolts and power shelf/its components.
Added mounting holes for 80 mm fan, as 120mm fan is too large and will not be used. Also adjusted the vent arcs so there is more room for air flow and less blocking from the arcs.
Added holes in panels for the power shelf mounting bolts, need to verify I didn't miss any

**Comment by camkab** [comment]
Vents have been positioned. The top plate will be mounted using rivet nuts so the bolts don't hit the fan in the back.  Planning on manufacturing Wednesday 4/11

**Comment by camkab** [comment]
HDPE went missing and is currently being worked on by Mish to figure out what happened to it. Meanwhile the panels were cut out of foam core as a stand in for demos. Foam core can be spun off as prototyping before we commit to material, for demo purposes. 
Due to the unexpected delays, the date has been moved back
